 - name: Кэширование
 uses: actions/cache@v5.0.3
 with:
 # Список файлов, каталогов и шаблонов с подстановочными знаками для кэширования и восстановления
 path: 
 # Явный ключ для восстановления и сохранения кэша
 key: 
 # Упорядоченная многострочная строка со списком ключей, соответствующих префиксу, которые используются для восстановления устаревшего кэша, если ключ не был найден в кэше.  Обратите внимание, что в этом случае функция cache-hit возвращает false. 
 restore-keys: # необязательно
 # Размер фрагмента, используемый для разделения больших файлов при загрузке, в байтах
 upload-chunk-size: # необязательно
 # Необязательный логический параметр, который при включении позволяет исполнителям Windows сохранять или восстанавливать кэши, которые можно восстановить или сохранить соответственно на других платформах
 enableCrossOsArchive: # необязательно, по умолчанию false
 # Завершает рабочий процесс, если запись в кэше не найдена
 fail-on-cache-miss: # необязательно, по умолчанию false
 # Проверить, существует ли запись в кэше для заданных входных данных (ключ, ключи восстановления), не загружая кэш 
 только для поиска: # необязательно, значение по умолчанию равно false
 # Запустите шаг post, чтобы сохранить кэш, даже если предыдущий шаг завершится неудачей 
 сохранять-всегда: # необязательно, значение по умолчанию равно false
 
